name: Run tests
on:
  push:
    branches: [master, main, dev]
  pull_request:
    types: [opened, edited]
permissions:
  actions: write
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['lts', '1', 'pre']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
    steps:
      - uses: actions/checkout@v4
      - name: Configure git for private repos
        run: git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
      - name: Dev unregistered dependencies
        run: |
          git clone https://github.com/nsiccha/TestModules.jl.git
          julia --project=. -e 'using Pkg; Pkg.develop(path="TestModules.jl")'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
